apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 655663222139.dkr.ecr.us-east-1.amazonaws.com/crud-app:react-express-mongodb-backend  # Replace with your backend Docker image>
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"  # Request 100 milliCPU (0.1 CPU core)
          limits:
            cpu: "500m"   # Limit to 500 milliCPU (0.5 CPU core)

