 frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 655663222139.dkr.ecr.us-east-1.amazonaws.com/crud-app:react-express-mongodb-frontend
          ports:
            - containerPort: 3000
          stdin: true

---

# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  resources:
    requests:
      cpu: "100m"  # Request 100 milliCPU (0.1 CPU core)
    limits:
      cpu: "500m"   # Limit to 500 milliCPU (0.5 CPU core)
  type: LoadBalancer
